version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - another-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: ./
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty12345"
    depends_on:
      - postgres
    volumes:
      - ./bot:/app

volumes:
  another-data: